version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
  
volumes:
  mariadb-data: